version: "3.8"
services:

  schedule-db:
    container_name: schedule-db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${AUTH_DATABASE_USER}
      - POSTGRES_PASSWORD=${AUTH_DATABASE_PASSWORD}
      - POSTGRES_DB=${AUTH_DATABASE_DB}
    ports:
      - '5432:5432'

  sample-schedule:
    image: 'sample-schedule:latest'
    build:
      context: .
    container_name: sample-schedule
    ports:
      - 8090:8090
    depends_on:
      - schedule-db